In [52]:
#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.feature_selection import SelectKBest,chi2
from sklearn.tree import DecisionTreeClassifier

In [36]:
#loading the dataset
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

#day 19 learnings
1) how big data ?

In [8]:
df.shape#so our data has 12 columns and around 891 rows

(891, 12)

2).how data looks like?

In [10]:
df.sample(8)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
197,198,0,3,"Olsen, Mr. Karl Siegwart Andreas",male,42.0,0,1,4579,8.4042,NaN,S
785,786,0,3,"Harmer, Mr. Abraham (David Lishin)",male,25.0,0,0,374887,7.2500,NaN,S
740,741,1,1,"Hawksford, Mr. Walter James",male,NaN,0,0,16988,30.0000,D45,S
106,107,1,3,"Salkjelsvik, Miss. Anna Kristine",female,21.0,0,0,343120,7.6500,NaN,S
298,299,1,1,"Saalfeld, Mr. Adolphe",male,NaN,0,0,19988,30.5000,C106,S
586,587,0,2,"Jarvis, Mr. John Denzil",male,47.0,0,0,237565,15.0000,NaN,S
754,755,1,2,"Herman, Mrs. Samuel (Jane Laver)",female,48.0,1,2,220845,65.0000,NaN,S
452,453,0,1,"Foreman, Mr. Benjamin Laventall",male,30.0,0,0,113051,27.7500,C111,C

In [14]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [16]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

inference=>1)Age has missing values 177 
           2)Cabin has 687 missing values out of 891 rows so we will drop this
           3)Embarked has 2 missing values

In [20]:
df.duplicated().sum()#no duplicate values

0

In [37]:
df['Family']=df['SibSp']+df['Parch']
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,3
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0

In [38]:
df.drop(columns=df.iloc[:,[0,3,6,7,8,10]],inplace=True)#removing columns Passengerid,Name,Cabin

In [97]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['Survived']),
                                                 df['Survived'],
                                                 test_size=0.2,
                                                random_state=42)
df

     Survived  Pclass     Sex   Age     Fare Embarked  Family
0           0       3    male  22.0   7.2500        S       1
1           1       1  female  38.0  71.2833        C       1
2           1       3  female  26.0   7.9250        S       0
3           1       1  female  35.0  53.1000        S       1
4           0       3    male  35.0   8.0500        S       0
..        ...     ...     ...   ...      ...      ...     ...
886         0       2    male  27.0  13.0000        S       0
887         1       1  female  19.0  30.0000        S       0
888         0       3  female   NaN  23.4500        S       3
889         1       1    male  26.0  30.0000        C       0
890         0       3    male  32.0   7.7500        Q       0

[891 rows x 7 columns]

#we will do eda later in this part but first make a pipeline so to revise the steps:
1)impute the missing values 
2)feature construction
3)handle categorical features
4)feature construction
5)feature scaling
6)model training

In [98]:
trns1=ColumnTransformer([('age_impute',SimpleImputer(strategy='mean'),[3]),
                        ('embark_impute',SimpleImputer(strategy='most_frequent'),[5])],
                        remainder='passthrough')

In [108]:
trns2=ColumnTransformer([
    ('ohe_sex_embarked',OneHotEncoder(sparse=False,drop='first',handle_unknown='ignore'),[2,5])
],remainder='passthrough')
trns2.fit(df)

# Get the number of output columns
# num_columns = trns2.transform(df).shape[1]
num_columns = trns2.transform(df)
num_columns.to_frame()
# print("Number of columns after transformation:", num_columns)#want to know no. of columns to apply scaling

D:\ana\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

AttributeError: 'numpy.ndarray' object has no attribute 'to_frame'

In [102]:
trns3=ColumnTransformer([('Scaling',StandardScaler(),slice(0,None))],remainder='passthrough')# Scaling all columns

In [103]:
trns4=DecisionTreeClassifier()

Creating pipeline

In [104]:
pipe=Pipeline([
   ( 'trns1',trns1),
    ('trns2',trns2),
    ('trns3',trns3),
    ('trns4',trns4)
])

In [105]:
pipe.fit(X_train,y_train)

D:\ana\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

ValueError: could not convert string to float: 'male'